baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs=false
title = "Istio学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
	# General information
	author = "敖小剑"
	keywords = "Istio,service mesh,服务网格,学习笔记,敖小剑"
	description = "Istio是一个连接，管理和保护微服务的开放平台。"
	copyright = "版权所有，转载请注明出处"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/skyao/learning-istio"
	
	version = ""
	logo = "images/logo.png"
	favicon = ""
	
	permalink = "#"
	
	# reward button, comment this to disable it
	reward = true
	
	# Custom assets
	custom_css = []
	custom_js  = []
	
	# Syntax highlighting theme
	highlight_css  = ""
	
	[params.palette]
		primary = "red"
		accent  = "teal"
	
	[params.font]
		text = "Ubuntu"
		code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"


[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 100

[[menu.main]]
	name   = "版本发布"
	identifier = "introduction-release"
	parent = "introduction"
	url    = "/introduction/release/"
	weight = 120

[[menu.main]]
	name   = "安装"
	identifier = "installation"
	url    = "/installation/"
	weight = 200

[[menu.main]]
	name   = "API"
	identifier = "api"
	url    = "/api/"
	weight = 300

[[menu.main]]
	name   = "MCP API"
	identifier = "api-mcp"
	parent = "api"
	url    = "/api/mcp"
	weight = 360

[[menu.main]]
	name   = "CRD"
	identifier = "crd"
	url    = "/crd/"
	weight = 400

[[menu.main]]
	name   = "Network CRD"
	identifier = "crd-network"
	parent = "crd"
	url    = "/crd/network/"
	weight = 410

[[menu.main]]
	name   = "Authentication CRD"
	identifier = "crd-authentication"
	parent = "crd"
	url    = "/crd/authentication/"
	weight = 420

[[menu.main]]
	name   = "Pilot"
	identifier = "pilot"
	url    = "/pilot/"
	weight = 500

[[menu.main]]
	name   = "Pilot Discovery"
	identifier = "pilot-discovery"
	parent = "pilot"
	url    = "/pilot/discovery/"
	weight = 510

[[menu.main]]
	name   = "Pilot Agent"
	identifier = "pilot-agent"
	parent = "pilot"
	url    = "/pilot/agent/"
	weight = 530

[[menu.main]]
	name   = "Sidecar Injector"
	identifier = "pilot-injector"
	parent = "pilot"
	url    = "/pilot/injector/"
	weight = 550

[[menu.main]]
	name   = "Pilot新动态"
	identifier = "pilot-trend"
	parent = "pilot"
	url    = "/pilot/trend/"
	weight = 590

[[menu.main]]
	name   = "Galley"
	identifier = "galley"
	url    = "/galley/"
	weight = 600

[[menu.main]]
	name   = "Galley的设计"
	identifier = "galley-design"
	parent = "galley"
	url    = "/galley/design"
	weight = 610


[[menu.main]]
	name   = "Mixer"
	identifier = "mixer"
	url    = "/mixer/"
	weight = 700

[[menu.main]]
	name   = "Mixer设计"
	identifier = "mixer-design"
	parent = "mixer"
	url    = "/mixer/design/"
	weight = 710

[[menu.main]]
	name   = "Proxy"
	identifier = "proxy"
	url    = "/proxy/"
	weight = 800

[[menu.main]]
	name   = "Mixer Cache"
	identifier = "mixercache"
	parent = "proxy"
	url    = "/proxy/cache/"
	weight = 820

[[menu.main]]
	name   = "Citadel"
	identifier = "citadel"
	url    = "/citadel/"
	weight = 900

[[menu.main]]
	name   = "周边生态"
	identifier = "ecosystem"
	url    = "/ecosystem/"
	weight = 2000

[[menu.main]]
	name   = "Kiali"
	identifier = "kiali"
	parent = "ecosystem"
	url    = "/ecosystem/kiali/"
	weight = 2020

[[menu.main]]
	name   = "Maistra"
	identifier = "maistra"
	parent = "ecosystem"
	url    = "/ecosystem/maistra/"
	weight = 2030



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


